name: Construir y Publicar en Docker Hub

# Esto indica que la acción se ejecutará cada vez que hagas un "push" a la rama main
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el código del repositorio
        uses: actions/checkout@v4

      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir y subir la imagen
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          
          tags: juanelsener1994/tp-simpsons-app:latest